@startuml
actor "Cliente" as actorCliente
boundary "<<Pantalla>>\nEquipos" as boundryPantallaEquipos

actorCliente -> boundryPantallaEquipos
activate boundryPantallaEquipos
   boundryPantallaEquipos -> boundryPantallaEquipos: getCiudades()
    activate boundryPantallaEquipos
        control "CiudadesController" as ciudadesController
            control "CiudadesModel" as ciudadesModel
           boundryPantallaEquipos -> ciudadesController: GET api/v1/ciudad: Ciudad[]
            activate ciudadesController
                ciudadesController -> ciudadesModel: getAllCiudad()
                activate ciudadesController
                    database "bd_comprodigios" as dbComprodigios
                    entity ciudades
                    activate ciudadesModel
                        activate ciudadesModel
                            ciudadesModel -> dbComprodigios: SQL query
                            dbComprodigios -> ciudades
                            dbComprodigios -> ciudadesModel: {id, pais, ciudad, codigoPostal}
                        deactivate

                    deactivate
                deactivate
        deactivate
    deactivate
deactivate